GRANT CREATE ON DATABASE spielwiese TO agentsmith;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO agentsmith;
GRANT DELETE ON ALL TABLES IN SCHEMA public TO agentsmith;
GRANT INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO agentsmith;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO agentsmith;
